version: '3'

services:
  api:
    container_name: wongames_api
    image: aleferreinert/won-games-api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_NAME: strapi
      STRIPE_KEY: $(NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY)
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: aleferreinert/won-games-database:latest
    ports:
      - '5432:5432'
